#!/usr/bin/env bash

# calculate power usage using /sys/*/power_now if available

if [ -f /sys/class/power_supply/BAT*/power_now ]; then
    cat /sys/class/power_supply/BAT*/power_now |awk '{ printf $1 / 1000000 }' | xargs printf "%.2f\n" |  awk '{ split($1, a, "e"); printf "%.2f\n", a[1] }' | sed 's/.*/\0 Watt/'

# calculate power usage using /sys/*/current_now & voltage_now   if available
elif [ -f /sys/class/power_supply/BAT*/current_now ]; then
    cat /sys/class/power_supply/BAT*/current_now /sys/class/power_supply/BAT*/voltage_now | xargs | awk '{print $1*$2/1e12}' | xargs printf "%.2f\n" |  awk '{ split($1, a, "e"); printf "%.2f\n", a[1] }' | sed 's/.*/\0 Watt/'
else
    echo "NULL"
fi

