#!/usr/bin/env bash

current_device=$(pactl list sinks | grep -i 'Active port' | grep -i 'speaker\|headphones' -o | awk '{gsub(/Speaker/, "🔊"); gsub(/Headphones/, "🎧"); print}')
current_value="<big>$(pactl list sinks | grep -i 'volume' | head -n1 | grep -Pi '\d+?%' -o | head -n1)</big>"
mute_value=$( pactl list sinks | grep -i 'mute' | head -n1 | grep -Pi 'yes|no' -o)

if [ "$mute_value" = "no" ]; then
    echo $current_device $current_value
else
    echo 🔇
fi
    
