-- require("userPlugins/cmp-config")
-- require('userPlugins/_telescope-setting')
-- require('userPlugins/fzflua')
-- require('userPlugins/lsp-config')
-- require('userPlugins/goto-config')
-- require('userPlugins/lspsaga-config')
require("userPlugins/treesitter")
-- require('userPlugins/lualine-config')
-- require('hop').setup()
require("userPlugins/tabbar-config")
-- require("userPlugins/staline-config")
-- require('userPlugins/nvimtree-config')
-- require('userPlugins/autopairs-config')
-- require('userPlugins/colorizer-config')
-- require('userPlugins/which-config')
--require('userPlugins/comment-config')
-- require('userPlugins/terminal-config')
require("userPlugins/symbolline-config")
-- require('userPlugins/null-config')
require("userPlugins/iswaaap-config")
-- require('userPlugins/indentline-config')
-- require('userPlugins/gitsigns-config')
-- require('userPlugins/jaq-config')
-- require('bqf').setup()
-- require('mkdir')
require("color-config")
