vim.g.mapleader = " "
local map = vim.api.nvim_set_keymap
map("x", "il", "g_o^", { noremap = true, silent = true })
map("o", "il", ":normal vil<cr>", { noremap = true, silent = true })
map("x", "al", "$o^", { noremap = true, silent = true })
map("o", "al", ":normal val<cr>", { noremap = true, silent = true })
map("n", "<leader>hh", ":call matchadd('LineHighlight','\\%'.line('.').'l')<cr>", { silent = true, noremap = true })
map("n", "<leader>hv", ":set nohls<bar>call clearmatches()<cr>", { silent = true, noremap = true })
map("n", "<leader>bo", ":Bo<cr>", { silent = true, noremap = true })
map("n", "<leader>be", ":Be<cr>", { silent = true, noremap = true })
map("n", "<C-y>", ':lua vim.lsp.buf.signature_help({border = "single"})<CR>', { noremap = true, silent = true })
map("i", "jk", "<Esc>", { silent = true })
map("i", "kj", "<Esc>", { silent = true })
map("n", "<leader>fw", "yiw<leader>fb<Esc>pi", { silent = true })
map("n", "<TAB>", ":bnext<CR>", { noremap = true, silent = true })
map("n", "<s-tab>", ":bprevious<CR>", { noremap = true, silent = true })
map("n", "<leader>d", ":bp<bar>sp<bar>bn<bar>bd!<CR>", { noremap = true, silent = true })
map("n", "<leader>,", ":source $MYVIMRC<bar>Be<CR>", { noremap = true, silent = true })
-- map('n','<C-b>',':so $HOME/.config/nvim/early.vim<CR>',{noremap=true,silent=true})
map("n", "<leader>k", "K", { noremap = true, silent = true })
map("n", "<leader>c", ":mks! $HOME/textedit/nvim/early.vim<bar>qall!<CR>", { noremap = true, silent = true })
map("n", "<leader>hw", ":HopWord<CR>", { noremap = true, silent = true })
map("n", "<leader>hp", ":HopPattern<CR>", { noremap = true, silent = true })
map("n", "<leader>hc", ":HopChar1<CR>", { noremap = true, silent = true })
map("n", "<leader>hC", ":HopChar2<CR>", { noremap = true, silent = true })
map("n", "<leader>hl", ":HopLine<CR>", { noremap = true, silent = true })
map("n", "<leader>hdw", "d:HopWord<CR>", { noremap = true, silent = true })
map("n", "<leader>hdp", "d:HopPattern<CR>", { noremap = true, silent = true })
map("n", "<leader>hdc", "d:HopChar1<CR>", { noremap = true, silent = true })
map("n", "<leader>hdC", "d:HopChar2<CR>", { noremap = true, silent = true })
map("n", "<leader>hdl", "d:HopLine<CR>", { noremap = true, silent = true })
map("n", "<leader>hkw", "c:HopWord<CR>", { noremap = true, silent = true })
map("n", "<leader>hkp", "c:HopPattern<CR>", { noremap = true, silent = true })
map("n", "<leader>hkc", "c:HopChar1<CR>", { noremap = true, silent = true })
map("n", "<leader>hkC", "c:HopChar2<CR>", { noremap = true, silent = true })
map("n", "<leader>hkl", "c:HopLine<CR>", { noremap = true, silent = true })
map("n", "<leader>hyw", "y:HopWord<CR>", { noremap = true, silent = true })
map("n", "<leader>hyp", "y:HopPattern<CR>", { noremap = true, silent = true })
map("n", "<leader>hyc", "y:HopChar1<CR>", { noremap = true, silent = true })
map("n", "<leader>hyC", "y:HopChar2<CR>", { noremap = true, silent = true })
map("n", "<leader>hyl", "y:HopLine<CR>", { noremap = true, silent = true })
map("n", "<leader>ha", ":set hls<CR>", { noremap = true, silent = true })
map("n", "<leader>r", ":Jaq<CR>", { noremap = true, silent = true })
-- map('n','<leader>f',':lua require("fzf-lua").files({cwd = "."})<CR>',{noremap=true,silent=true})
-- map('n','<leader>fq',':q<CR>',{noremap=true,silent=true})
-- map('n','<leader>fh',':lua require("fzf-lua").files({cwd ="/home/drkknght"})<CR>',{noremap=true,silent=true})
-- map('n','<leader>ft',':Telescope find_files<CR>',{noremap=true,silent=true})
-- map('n','<leader>fl',':FzfLua live_grep<CR>',{noremap=true,silent=true})
-- map("n", "<leader>y", '"+yy', { noremap = true, silent = true })
map("n", "<leader>y", "magg\"+yG'a", { noremap = true, silent = true })
map("n", "n", "nzz", { noremap = true, silent = true })
map("n", "N", "Nzz", { noremap = true, silent = true })
map("x", "J", ":move '>+1<CR>gv-gv", { noremap = true, silent = true })
map("x", "K", ":move '<-2<CR>gv-gv", { noremap = true, silent = true })
map("x", "<A-j>", ":move '>+1<CR>gv-gv", { noremap = true, silent = true })
map("x", "<A-k>", ":move '<-2<CR>gv-gv", { noremap = true, silent = true })
map("v", ">", ">gv", { noremap = true, silent = true })
map("v", "<", "<gv", { noremap = true, silent = true })
map("n", "<leader>z", ":e ~/.config/nvim/init.lua<cr>", { noremap = true, silent = true })
-- jump to next text objects
map("n", "<leader>n)", "/)<cr>", { noremap = true, silent = true })
map("n", "<leader>n(", "/(<cr>", { noremap = true, silent = true })
map("n", "<leader>m)", "?)<cr>", { noremap = true, silent = true })
map("n", "<leader>m(", "?(<cr>", { noremap = true, silent = true })
map("n", "<leader>n[", "/[<cr>", { noremap = true, silent = true })
map("n", "<leader>n]", "/]<cr>", { noremap = true, silent = true })
map("n", "<leader>m[", "?[<cr>", { noremap = true, silent = true })
map("n", "<leader>m]", "?]<cr>", { noremap = true, silent = true })
map("n", "<leader>n{", "/{<cr>", { noremap = true, silent = true })
map("n", "<leader>n}", "/}<cr>", { noremap = true, silent = true })
map("n", "<leader>m{", "?{<cr>", { noremap = true, silent = true })
map("n", "<leader>m}", "?}<cr>", { noremap = true, silent = true })
map("n", "<leader>n'", "/'<cr>", { noremap = true, silent = true })
map("n", "<leader>m'", "?'<cr>", { noremap = true, silent = true })
map("n", '<leader>n"', '/"<cr>', { noremap = true, silent = true })
map("n", '<leader>m"', '?"<cr>', { noremap = true, silent = true })
map("n", "<leader>n`", "/`<cr>", { noremap = true, silent = true })
map("n", "<leader>m`", "?`<cr>", { noremap = true, silent = true })
map("n", "<leader>ne", "/=\\+<cr>", { noremap = true, silent = true })
map("n", "<leader>me", "?=<cr>", { noremap = true, silent = true })
map("n", "<leader>na", "/+<cr>", { noremap = true, silent = true })
map("n", "<leader>ma", "?+<cr>", { noremap = true, silent = true })
map("n", "<leader>ns", "/-<cr>", { noremap = true, silent = true })
map("n", "<leader>ms", "?-<cr>", { noremap = true, silent = true })
map("n", "<leader>nd", "/_<cr>", { noremap = true, silent = true })
map("n", "<leader>md", "?_<cr>", { noremap = true, silent = true })
map("n", "<leader>nb", "//<cr>", { noremap = true, silent = true })
map("n", "<leader>mb", "?/<.\\{-}><cr>", { noremap = true, silent = true })
map("n", "<leader>nt", "/<.\\{-}><cr>", { noremap = true, silent = true })
map("n", "<leader>mt", "?><cr>", { noremap = true, silent = true })
map("n", "<leader>nn", "/\\d\\+<cr>", { noremap = true, silent = true })
map("n", "<leader>mn", "?\\d\\+<cr>", { noremap = true, silent = true })
map("n", "<leader>o", "o<Esc>k", { noremap = true, silent = true })
map("n", "<leader>oa", "o<Esc>kO<Esc>j", { noremap = true, silent = true })
map("n", "<leader>O", "O<Esc>j", { noremap = true, silent = true })
map("n", "<leader>nv", "/\\w\\+\\s*=\\s*<cr>", { noremap = true, silent = true })
map("n", "<leader>mv", "?\\w\\+\\s*=\\s*<cr>", { noremap = true, silent = true })
map("n", "]a", ":s/\\w\\+/'\\0',/g<bar>normal I= [<Esc>A]<Esc>I", { noremap = true, silent = true })
map("n", "]e", ":s/\\w\\+/\\0,/g<bar>normal I= [<Esc>A]<Esc>I", { noremap = true, silent = true })
-- map("n","dab","/(\\([a-zA-Z0-9,'-_]*\\|\\n\\))\\{-}<cr>:normal da(<cr>",{noremap=true,silent=true})
-- map("n","dib","/(\\([a-zA-Z0-9,'-_]*\\|\\n\\))\\{-}<cr>:normal di(<cr>",{noremap=true,silent=true})
-- map("n","diB","/{\\([a-zA-Z0-9,'-_]*\\|\\n\\)}\\{-}<cr>:normal di{<cr>",{noremap=true,silent=true})
-- map("n","daB","/{\\([a-zA-Z0-9,'-_]*\\|\\n\\)}\\{-}<cr>:normal da{<cr>",{noremap=true,silent=true})
