# copy this file /boot/efi/loader/entries/mint.conf
title Linux mint
linux /vmlinuz-6.2.9-4-liquorix-amd64
initrd /initrd.img-6.2.9-4-liquorix-amd64
options root=/dev/nvme0n1p2 loglevel=3 quiet systemd.mask=zfs.target ipv6.disable=1 mitigations=off nowatchdog amd-pstate=passive
