title Linux mint
linux /vmlinuz-5.15.0-56-generic
initrd /initrd.img-5.15.0-56-generic
options root=UUID=4fa5934a-6569-4ead-868f-bc61989ca7f1 loglevel=3 quiet systemd.mask=zfs.target ipv6.disable=1 mitigations=off nowatchdog amd-pstate=passive
