title Linux mint
linux /vmlinuz-5.15.0-56-generic
initrd /initrd.img-5.15.0-56-generic
options root=UUID=7baf6d43-5ff1-4a32-bf58-1ff2005ee341 loglevel=0 quiet systemd.mask=zfs.target ipv6.disable=1 mitigations=off nowatchdog amd-pstate=passive 
