# enables Xterm with 256 color support
set -g default-terminal "xterm-256color"

# enable mouse
set-option -g mouse on

# set -ga terminal-overrides ",*256col*:Tc"
# set -g default-terminal "xterm-256color"
# set-default colorset-option -ga terminal-overrides ",xterm-256color:Tc"
# set-option -sa terminal-overrides ',alacritty:RGB'

#terminal-overrides matches TERM outside tmux and allows you to modify the capabilities tmux uses when it talks to the terminal it is running it.
set-option -ga terminal-overrides ",xterm-256color:Tc"

# set prefix

set -g prefix C-e

# start window index from 1
set -g base-index 1

# start pane index from 1
set -g pane-base-index 1

# set statusline-style bold
set -g status-style bold

# set lenght of the session name to be atmost 50 chars
set -g status-left-length 50

# set foreground color for statusline
set -g status-fg colour232

# set bg color for status line
set -g status-bg colour25

# set default shell inside tmux
set -g default-shell $SHELL 

# set window status style color
set -g window-status-style fg=colour16

# set active window color
set -g window-status-current-style fg=colour16,bold,bg=colour28

# give names to windows automatically
set-window-option -g automatic-rename on


# set client terminal title
set-option -g set-titles on

# use vi or emac style bindings
setw -g mode-keys vi

# set escape waiting time for tmux
set -g escape-time 1

# unbind b
# unbind C-b
# bind 'b' copy-mode
# Vertical splits with v or C-v
unbind C-v
bind-key v split-window -h -c "#{pane_current_path}"
bind-key C-v split-window -h -c '#{pane_current_path}'
bind-key b break-pane -d

# Relaod the file with prefix r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# join panes from windows
bind-key -r C-y command-prompt -p "join pane from: "  "join-pane -h -s '%%'"

# bind-key x display-panes\; command-prompt -p "pane #: "  "swap-pane -t '%%'"

# Horizontal splits with v or C-h
unbind u
unbind C-u
bind-key u split-window -c "#{pane_current_path}"
bind-key C-u split-window -c "#{pane_current_path}"
# kill session fzf
unbind g
unbind C-g
bind-key g run-shell "fzf_tmux.sh ~/bin" 
# bind-key C-y send-keys  "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t" C-m
bind -n C-L display-popup -E "tmux_session_switch.sh"
bind -n C-s popup -h 70% -w 85% -E "tmux_create.sh"
bind -n C-k popup -E "tmux_kill.py"
# bind -n C-k new-window  vim
# bind  C-n new-window -E "tmux send-keys" #new-sinxiession

# Ctrl - t or t new window
unbind t
unbind C-t
unbind C-p
bind-key t new-window -c "#{pane_current_path}"
bind-key p new-window 

# bind-key -n M-t new-window
# Ctrl - o or o to kill panes
unbind o
unbind C-o
bind-key o kill-pane
bind-key C-o kill-server


# C + control q to kill session
unbind q
unbind C-q
bind-key q kill-session
# bind-key C-q kill-server

# Quick window selection
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# switch windows with the tab
# bind -n M-m previous-window
# bind -n M-n next-window

# Switching panes with ctrl
bind-key  l select-pane -R 
bind-key  h select-pane -L
bind-key  k select-pane -U
bind-key  j select-pane -D
# bind-key C-l send-prefix
bind-key C-e send-prefix

# enable mouse control (clickable windows, panes, resizeablepanes)
# ctrd-d to close windows
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# vi bindings for copy and paste
bind Escape copy-mode
bind -T copy-mode-vi 'v' send-keys -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-selection

# set-option -s set-clipboard off
# bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  
